[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

[colors.primary]
background = "#151515"
# opacity = 0.85
# blur = true

[font]
normal.family = "Liga SFMono Nerd Font"
size = 13

[cursor]
style = { shape = "Beam", blinking = "Off" }

[mouse]
hide_when_typing = true
