[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity = 0.85
blur = true

[font]
normal.family = "Liga SFMono Nerd Font"
size = 13

[cursor]
style = { shape = "Beam", blinking = "Off" }
