tap "asmvik/formulae"
tap "dlvhdr/formulae"
tap "epk/epk"
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae"
tap "morpho-lang/morpho"
tap "neur0map/tap"
tap "nikitabobko/tap"
tap "philpennock/protocols"
tap "sikarugir-app/sikarugir", "https://github.com/Sikarugir-App/homebrew-sikarugir"
tap "vldmrkl/formulae"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Run arbitrary commands when files change
brew "entr"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Render markdown on the CLI
brew "glow"
# Improved top (interactive process viewer)
brew "htop"
# GNOME XML library
brew "libxml2"
# Package manager for the Lua programming language
brew "luarocks"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Object-relational database system
brew "postgresql@18"
# Python version management
brew "pyenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Enables extra languages support for Tesseract
brew "tesseract-lang"
# Official tldr client written in Rust
brew "tlrc"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Markup-based typesetting system
brew "typst"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# GPU-accelerated terminal emulator
cask "alacritty"

cask "font-roboto-mono"
cask "font-roboto-mono-nerd-font"
cask "epk/epk/font-sf-mono-nerd-font"
cask "font-sf-mono-nerd-font-ligaturized"
# Cross-platform Git credential storage for multiple hosting providers
cask "git-credential-manager"
# Finder Toolbar app to open the current directory in Terminal or Editor
cask "openinterminal"
# Colour picker for colours onscreen
cask "pika"
# App that enables mouse-free UI interaction
cask "shortcat"
# Porting tool, to make Windows programs/games into native apps
cask "sikarugir-app/sikarugir/sikarugir"
# PDF viewer designed for reading research papers and technical books
cask "sioyek"
npm "corepack"
npm "surge"
